# Generated by Django 4.1.7 on 2023-11-05 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1', models.TextField(max_length=20)),
                ('card_2', models.TextField(max_length=20)),
                ('card_3', models.TextField(max_length=20)),
                ('card_4', models.TextField(max_length=20)),
                ('card_5', models.TextField(max_length=20)),
                ('max_player_num', models.PositiveIntegerField()),
                ('current_player_num', models.PositiveBigIntegerField(default=0)),
                ('coins', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_number', models.PositiveIntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory', models.DecimalField(decimal_places=2, max_digits=3)),
                ('card_1', models.TextField(max_length=20)),
                ('card_2', models.TextField(max_length=20)),
                ('is_win', models.BooleanField(blank=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('player_room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_numbers', models.PositiveIntegerField(default=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
